### ISSUE TITLE
Release initial 0.1.0 version

### ISSUE THREAD

**Issue by weppos** [dnsimple/terraform-dnsimple-cts#2]
A tagged version is required to release to the Terraform Registry.

<img width="490" alt="Screenshot 2022-04-12 at 16 35 29" src="https://user-images.githubusercontent.com/5387/162987956-59d61892-40be-44c4-bbaa-3b85789619f4.png">

**Comment by ecomba** [comment]
> @ecomba can you take care of prepping a release?
> 
> 

I'll look into it tomorrow!
