### ISSUE TITLE
Multiple creation of dnsimple record

### ISSUE THREAD

**Issue by Allan-Nava** [dnsimple/terraform-dnsimple-cts#5]
With this condition it registered 2 times because I have also the connect proxy
```

# Task Block
task {
  name        = "dnsimple-task"
  description = "Create/delete/update DNS records"
  module      = "dnsimple/cts/dnsimple"
  version    = "0.2.1"

  condition "services" {
    regexp = ".+"
    filter = "Service.Tags contains \"dnsimple\""
  }
  variable_files = ["/consul-terraform-sync/config/terraform.tfvars"]
}
```

How can I prevent the registration of sidecar proxy?

Thanks
Allan

**Comment by DXTimer** [comment]
@Allan-Nava thank you for bringing this to our attention. I was able to reproduce the behavior, but I am yet to inspect the events to see how we can differentiate proxy service events. I should have some time to debug and document how to handle connect proxy setup in the coming days.

Could you share the proxy service definitions which you registered at Consul?

**Comment by Allan-Nava** [comment]
> @Allan-Nava thank you for bringing this to our attention. I was able to reproduce the behavior, but I am yet to inspect the events to see how we can differentiate proxy service events. I should have some time to debug and document how to handle connect proxy setup in the coming days.
> 
> Could you share the proxy service definitions which you registered at Consul?

I solved in this way:

```

  condition "services" {
    regexp = ".+"
    filter = "Service.Kind != \"connect-proxy\" and Service.Tags contains \"dnsimple\""
  }
```

**Comment by Allan-Nava** [comment]
> > @Allan-Nava thank you for bringing this to our attention. I was able to reproduce the behavior, but I am yet to inspect the events to see how we can differentiate proxy service events. I should have some time to debug and document how to handle connect proxy setup in the coming days.
> > Could you share the proxy service definitions which you registered at Consul?
> 
> I solved in this way:
> 
> ```
> 
>   condition "services" {
>     regexp = ".+"
>     filter = "Service.Kind != \"connect-proxy\" and Service.Tags contains \"dnsimple\""
>   }
> ```

is possible to add the CName and other labels?

Thanks
Allan

**Comment by DXTimer** [comment]
It is something we are currently considering for the upcoming improvements we want to make in the integration. If you have any more suggestions or use cases please share them.

I will create a separate issue to track the use of different DNS record types.

**Comment by DXTimer** [comment]
An issue has been created to track use cases for other DNS record types #8. If you get a chance to share your ideal setup for the CNAME record and others in the ticket, I would appreciate it greatly.
Thank you again for helping us make this a better integration!

**Comment by DXTimer** [comment]
Closing as this has now been addressed.
